# home_app/templatetags/file_tags.py
from django import template

register = template.Library()

@register.filter
def mdi_class(extension):
    mapping = {
        '.pdf': 'mdi-file-pdf',
        '.docx': 'mdi-file-word',
        '.doc': 'mdi-file-word',
        '.xlsx': 'mdi-file-excel',
        '.xls': 'mdi-file-excel',
        '.pptx': 'mdi-file-powerpoint',
        '.ppt': 'mdi-file-powerpoint',
        '.jpg': 'mdi-file-image',
        '.jpeg': 'mdi-file-image',
        '.JPG': 'mdi-file-image',
        '.JPEG': 'mdi-file-image',
        '.png': 'mdi-file-image',
        '.PNG': 'mdi-file-image',
        '.gif': 'mdi-file-image',
        '.svg': 'mdi-file-image',
        '.bmp': 'mdi-file-image',
        '.tiff': 'mdi-file-image',
        '.ico': 'mdi-file-image',
        '.txt': 'mdi-file-document',
        '.rtf': 'mdi-file-document',
        '.csv': 'mdi-file-delimited',
        '.json': 'mdi-code-json',
        '.xml': 'mdi-xml',
        '.html': 'mdi-language-html5',
        '.htm': 'mdi-language-html5',
        '.css': 'mdi-language-css3',
        '.js': 'mdi-nodejs',
        '.ts': 'mdi-language-typescript',
        '.py': 'mdi-language-python',
        '.java': 'mdi-language-java',
        '.c': 'mdi-language-c',
        '.cpp': 'mdi-language-cpp',
        '.cs': 'mdi-language-csharp',
        '.php': 'mdi-language-php',
        '.rb': 'mdi-language-ruby',
        '.go': 'mdi-language-go',
        '.swift': 'mdi-language-swift',
        '.kt': 'mdi-language-kotlin',
        '.sh': 'mdi-console',
        '.bat': 'mdi-console',
        '.ps1': 'mdi-console',
        '.sql': 'mdi-database',
        '.md': 'mdi-note-text',
        '.yaml': 'mdi-code-braces',
        '.yml': 'mdi-code-braces',
        '.ini': 'mdi-settings',
        '.log': 'mdi-file-document-box',
        '.zip': 'mdi-folder-zip',
        '.rar': 'mdi-folder-zip',
        '.7z': 'mdi-folder-zip',
        '.tar': 'mdi-folder-zip',
        '.gz': 'mdi-folder-zip',
        '.xz': 'mdi-folder-zip',
        '.mp3': 'mdi-music',
        '.wav': 'mdi-music',
        '.flac': 'mdi-music',
        '.aac': 'mdi-music',
        '.ogg': 'mdi-music',
        '.wma': 'mdi-music',
        '.m4a': 'mdi-music',
        '.mp4': 'mdi-movie',
        '.avi': 'mdi-movie',
        '.mkv': 'mdi-movie',
        '.mov': 'mdi-movie',
        '.wmv': 'mdi-movie',
        '.flv': 'mdi-movie',
        '.webm': 'mdi-movie',
        '.eps': 'mdi-file-image',
        '.psd': 'mdi-file-image',
        '.ai': 'mdi-file-image',
        '.woff': 'mdi-alpha-w-circle',
        '.woff2': 'mdi-alpha-w-circle',
        '.ttf': 'mdi-alpha-t-circle',
        '.eot': 'mdi-alpha-e-circle',
        '.otf': 'mdi-alpha-o-circle',
        '.exe': 'mdi-cog',
        '.dll': 'mdi-cogs',
        '.apk': 'mdi-android',
        '.ipa': 'mdi-apple',
        '.deb': 'mdi-linux',
        '.rpm': 'mdi-linux',
        '.iso': 'mdi-disc',
        '.dmg': 'mdi-disc',
        '.pfg': 'mdi-file-document',
        '.tsx': 'mdi-language-typescript',
        '.ipynb': 'mdi-notebook',
    }
    
    return mapping.get(extension, '')