# Generated by Django 5.1.2 on 2024-11-03 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0001_initial"),
        ("home_app", "0002_alter_file_folder"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="folders",
                to="auth_app.group",
            ),
        ),
    ]
